apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-frontend
  template:
    metadata:
      labels:
        app: vite-frontend
    spec:
      containers:
        - name: vite-frontend
          image: surajshah/frontend:v2.9
          ports:
            - containerPort: 8080
          # env:
          #   - name: VITE_BACKEND_SERVER
          #     value: "http://10.244.1.5:5010"
---
apiVersion: v1
kind: Service
metadata:
  name: vite-frontend-service
spec:
  type: NodePort
  selector:
    app: vite-frontend  
  ports:
    - port: 8080        # Expose port 8080 inside the container
      targetPort: 8080   # The port on the container to which traffic will be forwarded
      nodePort: 30010   # The NodePort that will be exposed on the node