apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - name: guacamole
        image: guacamole/guacamole:1.5.5
        env:
          - name: GUACD_HOSTNAME
            value: "guacd"
          - name: MYSQL_HOSTNAME
            value: "mysql"
          - name: MYSQL_DATABASE
            value: "guacamole_db"
          - name: MYSQL_USER
            value: "guacamole_user"
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: guacamole-secret
                key: mysql-password
          - name: MYSQL_PORT
            value: "3306"
          - name: GUACD_PORT
            value: "4822"
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole-service
spec:
  type: NodePort
  selector:
    app: guacamole
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
spec:
  selector:
    app: guacamole
  ports:
      - protocol: TCP
        port: 8082  # Port exposed by the service
        targetPort: 8080  # Port on the container
