# Use an official Python runtime as the base image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . /app

# Install Python dependencies from requirements.txt
RUN pip install --upgrade pip

# Copy only the requirements.txt to leverage Docker cache
COPY requirements.txt /app/

# Install dependencies
RUN pip install -r requirements.txt

# Set environment variables for host and port
ENV HOST=0.0.0.0
ENV PORT=7001

# Expose the port the app will run on
EXPOSE 7001

# Command to run the FastAPI app using Uvicorn
CMD ["python", "./src/main_1.py"]
